include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    must_be_immutable: ignore
    deprecated_member_use: ignore
    use_build_context_synchronously: ignore
    unnecessary_brace_in_string_interps: ignore
    library_private_types_in_public_api: ignore
linter:
  rules:
    avoid_print: false
